@startuml
start
:開始;

while(ブロックが画面外に出るor指定ライン数を消す)
    :ブロックを生成;
    :ブロックの落下;
    :ブロックの移動および回転;
    :ブロックの接地判定;
    if(ラインが揃っているか) then(yes)
        :ラインを消す;
        :消えたラインの高さ分、ブロックを下げる;
    endif
endwhile(yes)
:リザルト画面;
:終了;
end
@enduml